### ISSUE TITLE
Doesn't work with argument options

### ISSUE THREAD

**Issue by ghost** [oclif/plugin-autocomplete#1]
As the title says, doesn't seem to work with argument options, with a `css:add` command, the following argument doesn't autocomplete.

```
static args = [
    {
        name: 'type',
        required: true,
        description: 'The type of file to generate',
        options: ['component', 'element', 'generic', 'object', 'setting', 'tool', 'utility']
    },
]
```

**Comment by mattgibson** [comment]
It would also be great to be able to specify options for non-strict commands that accept any number of arguments

**Comment by pzombade** [comment]
The bug still exists. Arguments do not auto-complete.
Even if we type a argument manually, then flags do not auto-complete. User need to manually type the flags too.

Its been a long time pending issue and important feature. I would appreciate if you guys could fix it on priority.
