### ISSUE TITLE
Bash autocomplete doesn't allow for filesystem completion after a command

### ISSUE THREAD

**Issue by spaghetti-is-pasta** [oclif/plugin-autocomplete#13]
If my command usage looks like:

```
   $ command sub-cmd <file>

```

And I type: `command sub-` `<tab><tab>` it properly completes. Yes!

*But*, when I type `command sub-cmd ~/` `<tab><tab>` to see files, say, in my homedir, I get nothing. Even though the usage of the command knows that a file is expected.

I've had to turns off bash completion entirely, as not being able to complete filename arguments off the filesystem is not great.

Any ideas??

**Comment by RasPhilCo** [comment]
As file completion is the "default" terminal completion we could fallback to that after completing commands. Good idea!
