### ISSUE TITLE
No code completion on windows

### ISSUE THREAD

**Issue by jmfrank63** [oclif/plugin-autocomplete#2]
As the source code and error message tells very obvious, there is no code completion on windows.
For a tool that is claiming to be cross platform this makes windows a second class citizen. Please provide code completion preferably for Powershell 6 (core), or instructions how one could help to get this running.

**Comment by jdxcode** [comment]
You're welcome to contribute!

**Comment by jmfrank63** [comment]
That's why I asked for instructions how to get this running. I have no idea how you are actually doing code completion and what prevented you in the first place to do it for windows. Could you be a little more specific than just a one liner, like any readings I could take and any suggested technology?

**Comment by jmfrank63** [comment]
Ok, I did some research on this. https://github.com/lzybkr/TabExpansionPlusPlus/ might be a way to go. Now I have no idea about your plugin at the moment, I hope you have more knowledge about this than about windows auto completion ;-) Would you agree that a PowerShell core is the best way to go for, as this is cross platform anyway?

**Comment by dprothero** [comment]
I will take a look at this. First up, tweak the Windows check so the autocomplete works if you're running Bash on Windows. Then I'll look at PowerShell.

**Comment by cristiand391** [comment]
plugin-autocomplete >= v.2.2.0 now supports PowerShell completion.
