### ISSUE TITLE
Support for aliases?

### ISSUE THREAD

**Issue by jdkdev** [oclif/plugin-autocomplete#226]
Hi!
thanks for the great plugin.  Does this have a way to capture the aliases as well?

Best,
Jordan

**Comment by cristiand391** [comment]
Hey, sorry for the late reply.

Both `zsh` and `bash` autocomplete implementation support command aliases.

Ref:
https://github.com/oclif/plugin-autocomplete/pull/331
https://github.com/oclif/plugin-autocomplete/pull/406
