### ISSUE TITLE
Trigger cache refresh after update of the CLI

### ISSUE THREAD

**Issue by ArchangelX360** [oclif/plugin-autocomplete#25]
As far as I understood, the cache is not refresh automatically. So any update could lead to an inconsistent autocompletion.

A simple implementation of that could be done with a `Hook<'update'>` however, in case of `@oclif/plugin-plugins` usage, then the order of the plugin update and the cache refresh is not guaranteed.

Do you have any suggestion on how to implement that?

**Comment by RasPhilCo** [comment]
We run a [recache hook] (https://github.com/heroku/cli/blob/8d9113ae58713775691adc01c3e8048d8cfcc6c2/packages/autocomplete/src/hooks/recache.ts) in the Heroku CLI.

We should add a note to the README about it.

**Comment by yoniamir** [comment]
Would be great if the autocomplete options can be calculated exactly at the time the user tries to autocomplete. This eliminates need to even refresh the autocomplete options, having to use hooks, and gives the best more accurate user experience.
