### ISSUE TITLE
Re-word installation instructions to be more copy-pasteable

### ISSUE THREAD

**Issue by childish-sambino** [oclif/plugin-autocomplete#26]
Need more clarity around _"If your terminal starts as a login shell"_. I had to go research this to figure out what I needed to do. Perhaps something like _"If you are on OS X, ..."_.

Instead of _"Add the autocomplete env var to your zsh profile and source it"_ perhaps _"Copy and paste the following line into your terminal"_ (and remove the `$` from the line so people don't copy it).

**Comment by pavelloz** [comment]
Where are those instructions?

Im trying to use this plugin but documentation is non existent.

**Comment by childish-sambino** [comment]
@pavelloz https://github.com/oclif/plugin-autocomplete/blob/80e02dce14d112e893a2bea014f1e2f3bd55b679/src/commands/autocomplete/index.ts#L37

**Comment by pavelloz** [comment]
Boy im glad i didnt hold my breath and just gave up on the feature ;)

**Comment by RasPhilCo** [comment]
@childish-sambino better copy sounds good! Though `$ do something` is a common notation convention.
