### ISSUE TITLE
Add fish auto complete

### ISSUE THREAD

**Issue by pksunkara** [oclif/plugin-autocomplete#3]
Fish is used by a lot of people too

**Comment by ryanwilsonperkin** [comment]
Hey, I'd like to take a crack at this because I use `fish`. Would the maintainers accept a PR for this behaviour?

**Comment by jdxcode** [comment]
we'd be happy to accept. Most of the oclif developers use fish ourselves actually

**Comment by ryanwilsonperkin** [comment]
Glad to hear it! I'm going to take a crack at this tonight
