### ISSUE TITLE
How to use the plugin correctly?

### ISSUE THREAD

**Issue by LimbersMay** [oclif/plugin-autocomplete#659]
Hi, good afternoon to everyone, I have a question, I've been reading the documentation https://www.npmjs.com/package/@oclif/plugin-autocomplete but I can't figure out how to use the plugin.

I've installed it via yarn add -D @oclif/plugin-autocomplete and I tried `oclif-example autocomplete zsh` but I get `zsh: command not found: oclif-example` from the terminal, the documentation also mention `Run <cli> autocomplete to generate the autocomplete files for your current shell.` but I still have the same problem `zsh: command not found: switch`. 

switch is a CLI command that I generate with oclif cli, I also added the plugin in the package.json 
`"plugins": [
      "@oclif/plugin-help",
      "@oclif/plugin-plugins",
      "@oclif/plugin-autocomplete"
    ],` but nothing works for me. 

If you can help me I would appreciate it very much
![2024-03-31-160347_1900x1030_scrot](https://github.com/oclif/plugin-autocomplete/assets/66845300/1a3624d3-4b58-4d9d-a9c5-47ed796ae383)
![2024-03-31-160933_1900x1030_scrot](https://github.com/oclif/plugin-autocomplete/assets/66845300/bc45c0ea-a7b8-44a9-9e07-d561affeb30c)

**Comment by mdonnalley** [comment]
@LimbersMay Sorry for the confusion. 

If you want to add `@oclif/plugin-autocomplete` to your CLI, then you need to do the following:
- `yarn add @oclif/plugin-autocomplete`
- add `@oclif/plugin-autocomplete` to the `plugins` list in package.json
- once you publish those changes, users can run `switch autocomplete` (or whatever your CLI's bin name is)
- you can also run the command locally with `bin/run.js autocomplete` or `bin/dev.js autocomplete`

If you want to install `@oclif/plugin-autocomplete` into an existing CLI, then you need to do the following:
- `<CLI> plugins install @oclif/plugin-autocomplete`
- then you can run `<CLI> autocomplete`

Hope that helps!
